name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: Testing
    env:
        DATABASE_HOSTNAME: postgres
        DATABASE_PORT: 5432
        DATABASE_PASSWORD: Zaisan12
        DATABASE_NAME: fastapi
        DATABASE_USERNAME: postgres
        SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
        ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRE_MINUTES: 300
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}-test
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Debug Hostname Resolution
        run: ping -c 4 postgres
      - name: Run PyTest
        run: |
          pip install pytest
          pytest
